service: blog
image: ermeson/blog

ssh:
  user: root
  keys: ['~/.ssh/hetzner']

servers:
  web:
    - 65.108.155.115

proxy:
  ssl: true
  host: 65.108.155.115
  app_port: 80
  healthcheck:
    path: /

registry:
  server: localhost:5555

builder:
  arch: amd64
  args:
    APP_ENV: production

env:
  clear:
    APP_ENV: production
