service: blog-api
image: ermeson/blog-api

ssh:
    user: root
    keys: ["~/.ssh/hetzner"]

servers:
    web:
        - 65.108.155.115

readiness_delay: 60
proxy:
    host: 65.108.155.115
    app_port: 80
    path_prefix: /api
    healthcheck:
        path: /up
        interval: 30
        timeout: 5

labels:
    traefik.http.routers.blog-api.tls: "true"
    traefik.http.routers.blog-api.tls.certresolver: "letsencrypt"

registry:
    server: localhost:5555

builder:
    arch: amd64

env:
    clear:
        CADDY_GLOBAL_OPTIONS: "admin off"
        APP_ENV: production
        DB_HOST: blog-api-psql
        DB_NAME: blog
        DB_USER: postgres
    secret:
        - DB_PASSWORD
        - TELEGRAM_API_TOKEN
        - TELEGRAM_USERNAME

accessories:
    psql:
        image: postgres:16-alpine
        host: 65.108.155.115
        network: kamal
        env:
            clear:
                POSTGRES_USER: postgres
                POSTGRES_DB: blog
            secret:
                - POSTGRES_PASSWORD
        directories:
            - data:/var/lib/postgresql/data
